[package]
name = "proc-injection"
version = "0.1.0"
edition = "2021"

[dependencies]
user32-sys = "0.2.0"
winapi = { version = "0.3.9", features = ["minwindef", "processthreadsapi", "ntdef", "winnt", "errhandlingapi", "memoryapi", "minwinbase", "handleapi"] }
